// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTmFuyI0fTnfl-MWghHx6inUpAEGqy034',
    appId: '1:148114786158:web:73053d76aba42609a7a37f',
    messagingSenderId: '148114786158',
    projectId: 'notes-2fd82',
    authDomain: 'notes-2fd82.firebaseapp.com',
    storageBucket: 'notes-2fd82.firebasestorage.app',
    measurementId: 'G-19J5F3433C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWw8IQSVLFkLjI65H6gpzom41cLmdo2nA',
    appId: '1:148114786158:android:a339c159e5b2a2dba7a37f',
    messagingSenderId: '148114786158',
    projectId: 'notes-2fd82',
    storageBucket: 'notes-2fd82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgW5IXQREISCDbkM_EBHdFSbD2wyGh8Zo',
    appId: '1:148114786158:ios:39fb3f8a586eb470a7a37f',
    messagingSenderId: '148114786158',
    projectId: 'notes-2fd82',
    storageBucket: 'notes-2fd82.firebasestorage.app',
    iosBundleId: 'com.example.noteWFirebase',
  );
}
